server:
  port: 12445
spring:
  data:
    mongodb:
      host: https://cccandidate-server-eastus.documents.azure.com:443
      port: 27017
      database: texhibit
    logger:
    name: com.texhibit
    level: info
    additivity: false
    AppenderRef:
      - ref: MongoAppender

Root:
  level: info
  AppenderRef:
    - ref: ConsoleAppender
    - ref: RollingFileAppender
