server:
  port: 12445
spring:
  data:
    mongodb:
      host: mongodb://cccandidate-server:APMtEUffS19GpEBARjEEDlPlCqgiW81bb4HICxEpq6ddK2KWprs3rnlEK5rGBd2oVslY8CJ9vFgvACDbWURMIQ==@cccandidate-server.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@cccandidate-server@
      port: 27017
      database: texhibit
    logger:
    name: com.texhibit
    level: info
    additivity: false
    AppenderRef:
      - ref: MongoAppender

Root:
  level: info
  AppenderRef:
    - ref: ConsoleAppender
    - ref: RollingFileAppender
