server:
  port: 12445
spring:
  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_STRING}  # MongoDB connection string from Azure
      database: ${MONGODB_DATABASE_NAME}  # Database name
   
