server:
  port: 12445
spring:
  data:
    mongodb:
      uri: https://cccandidate-server-eastus.documents.azure.com:443/  # MongoDB connection string from Azure
      database: texhibit  # Database name
   
