server:
  port: 12445
spring:
  data:
    mongodb:
      uri: mongodb://cccandidate-server:APMtEUffS19GpEBARjEEDlPlCqgiW81bb4HICxEpq6ddK2KWprs3rnlEK5rGBd2oVslY8CJ9vFgvACDbWURMIQ==@cccandidate-server.mongo.cosmos.azure.com:27017/?ssl=true&replicaSet=globaldb
      database: texhibit
   
